version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../knowledge-stocker/:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ../knowledge-stocker:/var/www/html

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=knowledge_db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    volumes:
      - ./phpmyadmin/sessions:/sessions
      - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php